TamProject/TAM/urls.py
from django.urls import path
from . import views

app_name = 'TAM'

urlpatterns = [
    path('', views.ContactList, name='home'),
    path('Contact/<str:pk>/', views.ContactDetials, name='ContactD'),
    path('create_contact/', views.createContact, name='create_contact'),
    path('update_contact/<str:pk>/', views.updateContact, name='update_contact'),
    path('delete_contact/<str:pk>/', views.updateContact, name='delete_contact'),

]

TamProject/TamProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('TAM.urls')),
]

TamProject/TAM/models.py
from django.db import models

# Create your models here.




class Name(models.Model):
    firstName = models.CharField(max_length=100, null=True)
    lastName = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.firstName+" "+self.lastName

class PhoneNumber(models.Model):
    country_code = (
        ('+966', 'Saudi Arabia'),
        ('+991', 'y'),
    )
    countryCode = models.CharField(max_length=200, null=True, choices=country_code)
    mNumber = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.countryCode+self.mNumber

class Contact(models.Model):
    name = models.ForeignKey(Name, on_delete=models.CASCADE)
    phoneNumber = models.ForeignKey(PhoneNumber, on_delete=models.CASCADE)

    def __str__(self):
        return self.name.firstName+" "+self.name.lastName

TamProject/TAM/views.py
from django.shortcuts import render, redirect
# from django.http import HttpResponse
from .form import *

# Create your views here.
def ContactList(request):
    contact = Contact.objects.all()
    context = {'contact': contact}
    return render(request, "TAM/home.html", context)

def ContactDetials(request,pk):
    contact = Contact.objects.get(id=pk)
    context = {'contact': contact}

    return render(request, 'TAM/contactDetails.html', context)

def createContact(request):
    form = ContactForm()
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {'form': form}
    return render(request, 'TAM/contact_form.html', context)

def updateContact(request, pk):
    contact = Contact.objects.get(id=pk)
    form = ContactForm(instance=contact)

    if request.method == "POST":
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {'form': form}
    return render(request, 'TAM/contact_form.html', context)

def deleteContact(request, pk):
    contact = Contact.objects.get(id=pk)
    form = ContactForm(instance=contact)
    if request.method == "POST":
        contact.delete()
        return redirect('/')

    context = {'contact': contact}
    return render(request, 'TAM/deleteContact.html', context)


def createContactPhoneNumber(request):
    form = PhoneNumberForm()
    if request.method == "POST":
        form = PhoneNumberForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {'form': form}
    return render(request, 'TAM/contact_form.html', context)


def createContactName(request):
    form = NameForm()
    if request.method == "POST":
        form = NameForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {'form': form}
    return render(request, 'TAM/contact_form.html', context)

TamProject/templates/TAM/contactDetails.html
{% extends 'TAM/main.html' %}
{% load static %}

{% block content %}


        <h3> Contact Name : {{ contact.name }}</h3>
        <h3> Contact Phone Number : {{ contact.phoneNumber }}</h3>


{% endblock %}

TamProject/templates/TAM/contact_form.html
{% extends 'TAM/main.html' %}
{% load static %}

{% block content %}

    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" name="Submit">
    </form>

{% endblock %}

TamProject/templates/TAM/deleteContact.html
{% extends 'TAM/main.html' %}
{% load static %}


{% block content %}
<p> Are you sure you want to delete {{ contact }}</p>

    <form action="{% url 'TAM:deleteContact.html' contact.id %}" method="POST">
        {% csrf_token %}
        <a href="{% url 'home' %}"> Cancel</a>
        <input type="submit" name="Submit">
    </form>
{% endblock %}

TamProject/templates/TAM/footer.html
<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-dark" href="#">TAM.com</a>
  </div>
  <!-- Copyright -->
</footer>

TamProject/templates/TAM/home.html
{% extends  'TAM/main.html' %}
{% load static %}

    {% block content %}
        {% for con in contact %}
            <a href="{% url 'TAM:ContactD' con.id %}">View</a>
            <p>Contact Name : {{ con.name }}</p>

        {% endfor %}

    {% endblock %}

TamProject/templates/TAM/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TAM</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

    {% include 'TAM/navbar.html' %}

    {% block content %}

    {% endblock %}

    {% include 'TAM/footer.html' %}

</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

TamProject/templates/TAM/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <img src="{% static 'images/header-logo.png' %}">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="home.html">Contacts <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'TAM:create_contact' %}">Add Contact</a>
      </li>
    </ul>
  </div>
</nav>